# each config file is used to create an object within kubernetes
## each api version contains different object types, use carefully
apiVersion: v1
# defines the type of object we want to make within kube
## pods are used to run a container
kind: Pod
metadata:
  name: client-pod
  labels:
    component: web
spec:
  containers:
    - name: client
      image: escobard/docker-aws-product-ui-prod
      ports:
        - containerPort: 3000