apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels:
    component: web
spec:
  containers:
    - name: client
      image: escobard/docker-aws-product-ui-prod
      ports:
        - containerPort: 3000