# deployment objects are used to intelligently control pod configuration
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
## all of these properties are editable and automatically update running pods
spec:
  replicas: 1
  ## kube uses this label to check which matching running pods it needs to update
  selector:
    matchLabels:
      component: web
  ## determines the configuration of each pod created by this deployment file
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: client
          image: escobard/docker-aws-product-ui-prod
          ports: 
            containerPort: 3000